### ISSUE TITLE
Add support for GPUs in TIRA

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#277]

**Comment by mam10eks** [comment]
A good way to do this seems to be setting an environment variable for the pipeline: https://python-gitlab.readthedocs.io/en/stable/gl_objects/pipelines_and_jobs.html#examples that controls the tags (default tag is CPU, is overwritten if this pipeline sets the variables) (needs to skip ci for the original commit.

**Comment by mam10eks** [comment]
The kubernetes gitlab runner does at the moment not support to specify GPU-Limits, but there is a merge request which implemented such a feature: https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/1526

At the moment, I would want to wait until this is merged into the official branch. Until then, I would follow the recommendation in this thread and use LimitRanges on the Namespace level in kubernetes, e.g., something like this:

```
kind: LimitRange
metadata:
  name: gpu-limit-range
spec:
  limits:
  - default:
      nvidia.com/gpu: 1
    defaultRequest:
      nvidia.com/gpu: 1
    type: Container
```
