### ISSUE TITLE
Show more Metadata for Running Docker Jobs

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#279]
We discussed this in the last TIRA meeting, and I think @MattiWe already had some Ideas to improve the details of running jobs shown in the frontend.

**Comment by mam10eks** [comment]
I now added more metadata in the backend that we now can show in the frontend in this commit: https://github.com/tira-io/tira/commit/f93726080010ad172b248a89bb1210e938d2ef75

For each job, the following information is available:
```
{'run_id': '2022-10-30-15-40-52', 'execution': {'scheduling': 'done', 'execution': 'done', 'evaluation': 'running'}, 'stdOutput': '', 'started_at': '2022-10-30-15-40-52', 'pipeline_name': 'eval---task-2-spoiler-generation-validation-20220924-training---princess-knight---2022-10-30-15-40-52', 'job_config': {'cores': '1 CPU Cores', 'ram': '10GB of RAM', 'dataset_type': 'training', 'dataset': 'task-2-spoiler-generation-validation-20220924-training', 'software_id': 'docker-software-17', 'task_id': 'clickbait-spoiling', 'software_name': 'express-pitch', 'image': 'registry.webis.de/code-research/tira/tira-user-princess-knight/naive-baseline-task2:0.0.1', 'command': '/naive-baseline-task-2.py --input $inputDataset/input.jsonl --output $outputDir/run.jsonl'}}
```

**Comment by MattiWe** [comment]
The `job_config` object is only added if I set `force_cache_refresh=True` on `yield_all_running_pipelines`

I think that's a bug.

**Comment by MattiWe** [comment]
I also don't think the values are correct. For software during execution I get:
```
execution:
    evaluation: "pending"
    execution: "running"
    scheduling: "done"
job_config:
    cores: "1 CPU Cores"
    dataset: "Loading..."
    dataset_type: "Loading..."
    gpu: "Loading..."
    ram: "10GB of RAM"
    software_id: "Loading..."
    task_id: "Loading..."
pipeline_name: "eval---task-2-spoiler-generation-validation-20220924-training---princess-knight---2022-11-02-12-17-25"
run_id: "2022-11-02-12-17-25"
started_at: "2022-11-02-12-17-25"
stdOutput: "..."
```

So either `prepare_environment_job` is None or whatever happens in the `except: pass`


Can you do me a favor and refactor this function so
  - the expected fields are always there, or
  - I get a meaningful indicator as to not expect something. It is really hard to render otherwise.
