### ISSUE TITLE
Liveness Check for GRPC Server

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#305]
I now noticed the following behaviour multiple times: The GRPC server fails to process requests when there are some problems with ceph.

Then, the calls are not successful (nothing changed in the database), and the log contains entries like :

```
	status = StatusCode.UNKNOWN
	details = "Exception calling application: [Errno 107] Socket not connected: '/mnt/ceph/tira/data/runs/touche-23-task-2-validation-re-rank-default-text-20221122-training/touche23-test-maik/2022-11-22-16-42-25/run.prototext'"
	debug_error_string = "{"created":"@1669131967.948182350","description":"Error received from peer ipv4:141.54.132.1:31553","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Exception calling application: [Errno 107] Socket not connected: '/mnt/ceph/tira/data/runs/touche-23-task-2-validation-re-rank-default-text-20221122-training/touche23-test-maik/2022-11-22-16-42-25/run.prototext'","grpc_status":2}"
```

When I manually restart the GRPC Server, everything works fine again.

We should probably add a liveness probe in this container that checks that the cephfs is properly mounted so that the pods automatically restart in cases as above.

**Comment by mam10eks** [comment]
I now checked this in a failed pod: running `ls /mnt/ceph/tira` already failed. So I added a liveness probe:

```
        livenessProbe:
          exec:
            command:
            - ls
            - /mnt/ceph/tira
          initialDelaySeconds: 5
          periodSeconds: 5
```

and ensured that two GRPC servers run in parallel (`  replicas: 2`).
